const fs = require('fs');

const hindiDict = {
    'dashboard': 'डैशबोर्ड',
    'alerts': 'अलर्ट',
    'maintenance': 'रखरखाव',
    'compliance': 'अनुपालन',
    'anomalies': 'विसंगतियाँ',
    'organization': 'संगठन',
    'devices': 'उपकरण',
    'total_devices': 'कुल उपकरण',
    'active_alerts': 'सक्रिय अलर्ट',
    'city_wards': 'शहर के वार्ड',
    'live': 'लाइव',
    'refresh': 'रिफ्रेश',
    'export': 'रिपोर्ट निर्यात करें',
    'trigger_alert': 'SMS अलर्ट भेजें',
    'welcome': 'स्वागत है',
    'city_admin': 'शहर व्यवस्थापक',
    'industry_owner': 'उद्योग मालिक',
    'vehicle_owner': 'वाहन मालिक',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'success': 'सफलता',
    'cancel': 'रद्द करें',
    'save': 'सहेजें',
    'delete': 'हटाएं',
    'edit': 'संपादित करें',
    'add': 'जोड़ें',
    'close': 'बंद करें',
    'submit': 'जमा करें',
    'logout': 'लॉग आउट',
    'login': 'लॉग इन',
    'register': 'पंजीकरण',
    'settings': 'सेटिंग्स',
    'note': 'नोट',

    // ===== VEHICLE OWNER DASHBOARD =====
    'vehicle_dashboard': 'वाहन डैशबोर्ड',
    'emission_monitoring': 'उत्सर्जन निगरानी',
    'pause_live': 'लाइव रोकें',
    'resume_live': '▶ लाइव फिर से शुरू करें',
    'export_logs': 'लॉग निर्यात करें',
    'emission_health': 'उत्सर्जन स्वास्थ्य',
    'co_level': 'CO स्तर',
    'next_service': 'अगली सर्विस',
    'emission_health_score': 'उत्सर्जन स्वास्थ्य स्कोर',
    'live_sensors': 'लाइव सेंसर्स',
    'data_source': 'डेटा स्रोत',
    'usb_sensor_realtime': 'USB सेंसर (रीयल-टाइम)',
    'mqtt_sensor_realtime': 'MQTT/WiFi सेंसर (रीयल-टाइम)',
    'sim_engine_traffic': 'सिमुलेशन इंजन (ट्रैफिक मॉडल)',
    'schedule_maintenance': 'रखरखाव शेड्यूल करें',
    'weekly_emission_trend': 'साप्ताहिक उत्सर्जन प्रवृत्ति',
    'weekdays_higher_desc': 'कार्यदिवसों में अधिक उत्सर्जन (अधिक ट्रैफ़िक) होता है, सप्ताहांत में कम',
    'connecting_vehicle_sim': 'वाहन सिमुलेशन से कनेक्ट हो रहा है...',
    'excellent': 'उत्कृष्ट',
    'good': 'अच्छा',
    'need_improvement': 'सुधार की आवश्यकता है',
    'poor': 'खराब',
    'score_excellent_desc': 'उत्कृष्ट उत्सर्जन! आपका वाहन साफ चल रहा है।',
    'score_good_desc': 'अच्छा प्रदर्शन — उत्सर्जन सुरक्षित सीमा के भीतर है।',
    'score_improve_desc': 'मध्यम प्रदूषण का पता चला — इको-ड्राइविंग की सिफारिश की जाती है।',
    'score_poor_desc': 'उच्च प्रदूषण स्तर — जल्द से जल्द अपने वाहन की सर्विस कराएं।',
    'poor_emission_title': '🚨 खराब उत्सर्जन स्तर!',
    'improve_emission_title': '⚠️ उत्सर्जन में सुधार की आवश्यकता',
    'poor_emission_desc': 'जुर्माने से बचने के लिए कृपया तुरंत अपने वाहन की सर्विस कराएं।',
    'improve_emission_desc': 'स्मूथ एक्सीलरेशन की कोशिश करें, आइडलिंग से बचें।',
    'health_score_is': 'स्वास्थ्य स्कोर है',
    'legend_poor': '< 50 खराब',
    'legend_improve': '50–80 सुधार की आवश्यकता',
    'legend_good': '80–90 अच्छा',
    'legend_excellent': '> 90 उत्कृष्ट',
    'traffic': 'ट्रैफिक',
    'ambient': 'परिवेश',
    'engine': 'इंजन',
    'priority': 'प्राथमिकता',
    'loading_ml': 'ML लोड हो रहा है...',
    'days': 'दिन',

    // ===== USB / WIFI BUTTONS =====
    'wifi': 'WiFi',
    'wifi_connected': 'WiFi कनेक्टेड',
    'usb': 'USB',
    'usb_connected': 'USB कनेक्टेड',
    'usb_na': 'USB उपलब्ध नहीं',
    'usb_error': 'USB त्रुटि',
    'connecting_dots': 'कनेक्ट हो रहा है...',

    // ===== NOTIFICATION BELL =====
    'notifications': 'सूचनाएं',
    'mark_all_read': 'सभी को पढ़ा हुआ चिह्नित करें',
    'all_caught_up': 'सब पढ़ लिया!',
    'notif_high_emission': 'उच्च उत्सर्जन अलर्ट',
    'notif_high_emission_msg': 'CO स्तर सुरक्षित सीमा से अधिक हो गया।',
    'notif_maintenance': 'रखरखाव अनुस्मारक',
    'notif_maintenance_msg': 'निर्धारित सेवा 30 दिनों के भीतर देय है।',
    'notif_report': 'रिपोर्ट तैयार है',
    'notif_report_msg': 'साप्ताहिक उत्सर्जन रिपोर्ट उपलब्ध है।',
    'ago_5m': '5 मिनट पहले',
    'ago_2h': '2 घंटे पहले',
    'ago_1d': '1 दिन पहले',

    // ===== TIMELINE PAGE =====
    'emission_timeline': 'उत्सर्जन टाइमलाइन',
    'timeline_desc': 'MH-31-AB-1234 के लिए उत्सर्जन घटनाओं का पूरा इतिहास',
    'event_log': 'इवेंट लॉग',
    'engine_started': 'इंजन शुरू हुआ',
    'pm25_spike': 'PM2.5 स्पाइक का पता चला',
    'levels_normalized': 'उत्सर्जन स्तर सामान्य हो गया',
    'highway_mode': 'राजमार्ग मोड चालू हुआ',
    'engine_stopped': 'इंजन बंद हो गया',
    'co_spike': 'CO स्पाइक – 22 ppm',
    'auto_alert_sent': 'ऑटो अलर्ट भेजा गया',

    // ===== MAINTENANCE PAGE =====
    'maintenance_subtitle': 'आपके वाहन के लिए आगामी और देय रखरखाव कार्य',
    'service_schedule': 'सेवा अनुसूची',
    'oil_change': 'तेल परिवर्तन',
    'air_filter': 'एयर फिल्टर रिप्लेसमेंट',
    'emission_system_check': 'उत्सर्जन प्रणाली जांच',
    'tyre_rotation': 'टायर रोटेशन',
    'brake_inspection': 'ब्रेक निरीक्षण',
    'upcoming': 'आगामी',
    'due': 'देय',
    'overdue': 'अतिदेय',
    'book_service': 'सेवा बुक करें',
    'booked': '✓ बुक किया गया',

    // ===== ECO TIPS PAGE =====
    'eco_tips': 'इको टिप्स',
    'eco_tips_desc': "उत्सर्जन कम करने के लिए उपयोगी टिप्स",
    'smooth_accel_title': 'स्मूथ एक्सीलरेशन',
    'smooth_accel_desc': 'धीरे-धीरे एक्सीलरेट करने से ईंधन की कम खपत होती है और उत्सर्जन कम होता है।',
    'reduce_idling_title': 'इंजन आइडलिंग कम करें',
    'reduce_idling_desc': 'अनावश्यक उत्सर्जन में कटौती के लिए 60 सेकंड से अधिक समय तक रुकने पर इंजन बंद कर दें।',
    'tyre_pressure_title': 'टायर का दबाव बनाए रखें',
    'tyre_pressure_desc': 'उचित हवा वाले टायर ईंधन दक्षता में 3% सुधार कर सकते हैं और CO₂ कम कर सकते हैं।',
    'higher_gears_title': 'उच्च गियर का प्रयोग करें',
    'higher_gears_desc': 'उच्च गियर में शिफ्ट करके कम आरपीएम पर ड्राइविंग ईंधन की खपत काफी कम करता है।',
    'regular_service_title': 'नियमित सर्विसिंग',
    'regular_service_desc': 'एक अच्छी तरह से बनाए रखा गया इंजन 10-30% कम प्रदूषक छोड़ता है।',
    'plan_route_title': 'मार्ग की योजना बनाएं',
    'plan_route_desc': 'यातायात की भीड़ से बचें।',
    'driving': 'ड्राइविंग',
    'tyres': 'टायर',
    'planning': 'योजना',
    'high_impact': 'उच्च प्रभाव',
    'medium_impact': 'मध्यम प्रभाव',
    'low_impact': 'कम प्रभाव',

    // ===== GENERATOR DASHBOARD =====
    'generator_dashboard': 'जनरेटर डैशबोर्ड',
    'dg_unit_desc': 'DG यूनिट #1 · प्रदर्शन की निगरानी और उत्सर्जन नियंत्रण',
    'total_runtime': 'कुल रनटाइम',
    'emission_level': 'उत्सर्जन स्तर',
    'fuel_efficiency': 'ईंधन दक्षता',
    'next_maintenance': 'अगला रखरखाव',
    'runtime_vs_emission': 'रनटाइम बनाम उत्सर्जन विश्लेषण',
    'control_panel': 'नियंत्रण कक्ष',
    'status': 'स्थिति',
    'running': 'चल रहा है',
    'stopped': 'रुका हुआ',
    'operating_within_limits': 'उत्सर्जन सीमा के भीतर चल रहा है',
    'generator_offline': 'जनरेटर ऑफ़लाइन है',
    'temperature': 'तापमान',
    'live_emission': 'लाइव उत्सर्जन',
    'auto_shutdown': 'ऑटो शटडाउन',
    'auto_shutdown_desc': 'महत्वपूर्ण उत्सर्जन (>65 ppm) पर रोकें',
    'auto_shutdown_trigger': 'ऑटो शटडाउन ट्रिगर होगा',
    'stop_generator': '⏹ जनरेटर रोकें',
    'start_generator': '▶ जनरेटर शुरू करें',
    'weekly_fuel_efficiency': 'साप्ताहिक ईंधन दक्षता बनाम लक्ष्य',
    'fuel_tip_title': 'ईंधन दक्षता टिप',
    'fuel_tip_desc': 'दक्षता में सुधार करने के लिए पीक अवधि (8 AM–12 PM) के दौरान भार कम करें।',
    'emission_threshold_warn': '⚠️ उत्सर्जन सीमा से ऊपर (65 ppm)। भार कम करने पर विचार करें।',

    // ===== GENERATOR LOGS =====
    'emission_logs': 'उत्सर्जन लॉग',
    'logs_desc': 'DG सेट यूनिट #1 के लिए प्रति घंटा उत्सर्जन लॉग',
    'export_csv': 'CSV निर्यात करें',
    'timestamp_col': 'समय',
    'emission_col': 'उत्सर्जन (ppm)',
    'load_col': 'भार (%)',
    'fuel_col': 'ईंधन (L/h)',
    'temp_col': 'तापमान (°C)',
    'status_col': 'स्थिति',
    'normal': 'सामान्य',
    'alert': 'अलर्ट',

    // ===== GENERATOR PERFORMANCE =====
    'performance': 'प्रदर्शन',

    // ===== CITY ADMIN DASHBOARD =====
    'city_dashboard': 'शहर डैशबोर्ड',
    'physics_simulation': 'भौतिकी-आधारित सिमुलेशन इंजन',
    'avg_aqi': 'औसत शहर AQI',
    'ward_details': 'वार्ड विवरण',
    'forecast': '72-घंटे AQI पूर्वानुमान',
    'ward_comparison': 'वार्ड तुलना (लाइव)',
    'hourly_trend': '24-घंटे की प्रवृत्ति',
    'aqi_level': 'AQI स्तर',
    'pollutants': 'प्रदूषक',
    'pm25': 'PM2.5 (μg/m³)',
    'co': 'CO (ppm)',
    'nox': 'NOx (ppm)',
    'co2': 'CO₂ (ppm)',
    'heatmap': 'रीयल-टाइम हीटमैप',
    'city_aqi_heatmap': 'शहर AQI हीटमैप',
    'warnings': 'वार्ड चेतावनियाँ',
    'critical': 'गंभीर',
    'moderate': 'मध्यम',
    'aqi_good': 'अच्छा',
    'aqi_moderate': 'मध्यम',
    'aqi_unhealthy': 'अस्वस्थ',
    'aqi_scale': 'AQI पैमाना',
    'aqi_good_range': 'अच्छा (0-50)',
    'aqi_moderate_range': 'मध्यम (51-100)',
    'aqi_unhealthy_range': 'अस्वस्थ (101+)',
    'online': 'ऑनलाइन',
    'offline': 'ऑफ़लाइन',
    'all_monitored': 'सभी मॉनिटर किए गए',
    'threshold_violations': 'सीमा का उल्लंघन',
    'humidity': 'नमी',
    'wind': 'हवा',
    'city': 'शहर',
    'correlated_pollutant_data': 'सिमुलेशन से संबंधित प्रदूषक डेटा',
    'forecast_description': '📊 ऐतिहासिक डेटा पर ML मॉडल से पूर्वानुमान।',
    'connecting_simulation': 'सिमुलेशन इंजन से जुड़ रहा है...',
    'sensor_confidence': 'सेंसर आत्मविश्वास',
    'confidence_score': 'आत्मविश्वास स्कोर',
    'calibration_needed': 'कैलिब्रेशन आवश्यक',
    'hardware_failure_detected': 'हार्डवेयर विफलता का पता चला',
    'anomaly_spikes': 'विसंगति स्पाइक्स',
    'sensor_health': 'सेंसर स्वास्थ्य',
    'fair': 'औसत',
    'sensor_calibration_warning': 'सेंसर कैलिब्रेशन की आवश्यकता है - रीडिंग गलत हो सकती है',
    'hardware_inspection_warning': 'संभावित हार्डवेयर विफलता - निरीक्षण की आवश्यकता है',
    'recommendations': 'सिफारिशें',

    // ===== ALERTS PAGE =====
    'alert_desc': 'अलर्ट कैसे काम करते हैं: इंजन AQI, PM2.5, CO, और NOx सीमाओं की निगरानी करता है।',
    'all_clear': 'सब साफ़ है!',
    'no_alerts': 'इस समय कोई उल्लंघन नहीं।',
    'resolve': 'समाधान करें',
    'message_sent': 'WhatsApp अलर्ट भेजा गया',
    'alert_details': 'अलर्ट विवरण',
    'threshold': 'सीमा',
    'current_value': 'वर्तमान मूल्य',
    'last_updated': 'अंतिम अपडेट',
    'alert_status': 'अलर्ट की स्थिति',
    'active': 'सक्रिय',
    'resolved': 'हल हो गया',
    'restore_resolved': 'पुनर्स्थापित करें',
    'resolved_alerts': 'हल किए गए अलर्ट',

    // ===== POLICY PAGE =====
    'policy_config': 'नीति कॉन्फ़िगरेशन',
    'policy_desc': 'शहर-व्यापी उत्सर्जन नीतियां प्रबंधित करें',
    'active_policies': 'सक्रिय नीतियां',
    'saved': 'सहेजा गया',
    'read_only': 'केवल पढ़ने के लिए',
    'pm25_threshold': 'PM2.5 अलर्ट सीमा',
    'pm25_threshold_desc': 'किसी भी वार्ड में PM2.5 इस स्तर से अधिक होने पर ऑटो-अलर्ट।',
    'aqi_red_alert': 'AQI रेड अलर्ट स्तर',
    'aqi_red_alert_desc': 'AQI इस मूल्य से अधिक होने पर शहर-व्यापी सलाह ट्रिगर करें।',
    'notif_cooldown': 'अधिसूचना कूलडाउन',
    'notif_cooldown_desc': 'एक ही वार्ड के लिए बार-बार अलर्ट के बीच न्यूनतम समय।',
    'auto_shutdown_limit': 'ऑटो-शटडाउन जनरेटर सीमा',
    'auto_shutdown_limit_desc': 'इस सीमा को पार करने वाले जनरेटर को ऑटो-शटडाउन मिलता है।',
    'data_retention': 'डेटा प्रतिधारण अवधि',
    'data_retention_desc': 'रॉ सेंसर डेटा कितने समय तक संग्रहीत किया जाता है।',
    'emergency_broadcast': 'आपातकालीन प्रसारण',
    'emergency_broadcast_desc': 'AQI > रेड अलर्ट के दौरान पंजीकृत निवासियों को SMS भेजें।',
    'enabled': 'सक्रिय',

    // ===== INDUSTRY DASHBOARD =====
    'industry_dashboard': 'उद्योग डैशबोर्ड',
    'compliant': 'अनुपालक',
    'warning': 'चेतावनी',
    'non_compliant': 'गैर-अनुपालक',
    'chamber_emissions': 'चेंबर उत्सर्जन बनाम सीमा',
    'compliance_trend': 'अनुपालन प्रवृत्ति',
    'chamber': 'चेंबर',
    'emission_limit': 'उत्सर्जन सीमा',
    'current_emission': 'वर्तमान उत्सर्जन',
    'capacity': 'क्षमता',
    'cpcb_limits': 'CPCB/SPCB सीमाएं',
    'compliance_report': 'अनुपालन रिपोर्ट',
    'last_inspection': 'अंतिम निरीक्षण',
    'next_inspection': 'अगला निरीक्षण',

    // ===== ANOMALIES =====
    'detected_anomalies': 'खोजी गई विसंगतियाँ',
    'no_anomalies': 'कोई विसंगति नहीं मिली',
    'anomaly_score': 'विसंगति स्कोर',
    'anomaly_type': 'विसंगति प्रकार',
    'severity': 'गंभीरता',
    'high': 'उच्च',
    'medium': 'मध्यम',
    'low': 'निम्न',
    'investigate': 'जांच करें',

    // ===== ORGANIZATION =====
    'employees': 'कर्मचारी',
    'facilities': 'सुविधाएं',
    'facility_name': 'सुविधा का नाम',
    'facility_type': 'सुविधा का प्रकार',
    'location': 'स्थान',
    'employee_count': 'कर्मचारी संख्या',

    // ===== WARD ANALYTICS =====
    'ward_analytics': 'वार्ड विश्लेषिकी',
    'select_ward': 'वार्ड चुनें',
    'hourly_data': 'प्रति घंटा डेटा',
    'daily_average': 'दैनिक औसत',
    'weekly_average': 'साप्ताहिक औसत',
    'monthly_trend': 'मासिक प्रवृत्ति',
    'pollutant_breakdown': 'प्रदूषक टूटना',

    // ===== PREDICTIONS =====
    'predictions': 'भविष्यवाणियां',
    'aqi_forecast': 'AQI पूर्वानुमान',
    'forecast_period': 'पूर्वानुमान अवधि',
    'confidence_level': 'आत्मविश्वास स्तर',
    'predicted_aqi': 'अनुमानित AQI',
    'forecast_details': 'पूर्वानुमान विवरण',

    // ===== AUTH =====
    'welcome_back': 'वापसी पर स्वागत है',
    'sign_in_desc': 'अपने इकोट्रॉनिक्स खाते में साइन इन करें',
    'quick_demo': 'त्वरित डेमो लॉग इन',
    'or_manual': 'या मैन्युअल रूप से साइन इन करें',
    'email_address': 'ईमेल पता',
    'password': 'पासवर्ड',
    'sign_in': 'साइन इन करें',
    'signing_in': 'साइन इन हो रहा है...',
    'no_account': "खाता नहीं है?",
    'sign_up': 'साइन अप करें',

    // ===== MISC =====
    'language': 'भाषा',
    'english': 'English',
    'tamil': 'हिंदी',
    'hindi': 'हिंदी',
    'copyright': '© 2026 EcoTronics. सर्वाधिकार सुरक्षित।',
    'timeline': 'समयरेखा',
};

let fileContent = fs.readFileSync('src/i18n/translations.ts', 'utf8');

const insertStr = `
    hi: ${JSON.stringify(hindiDict, null, 8).replace(/\\}$/, '    }')},
`;
fileContent = fileContent.replace(/export type Language = 'en' \\| 'ta';/, "export type Language = 'en' | 'ta' | 'hi';");

let replaced = fileContent.replace(/\\s*\\};\\s*export type Language/, ",\\n" + insertStr + "\\n};\\n\\nexport type Language");

fs.writeFileSync('src/i18n/translations.ts', replaced);
console.log('Hindi added successfully!');
