"""
Subscription Plans — EcoTronics SaaS
"""

from enum import Enum


class PlanName(str, Enum):
    FREE = "free"
    STARTER = "starter"
    PROFESSIONAL = "professional"
    ENTERPRISE = "enterprise"


PLANS = {
    "free": {
        "name": "free",
        "display_name": "Free",
        "tagline": "Try EcoTronics with no commitment",
        "price_monthly": 0,
        "price_annual": 0,
        "currency": "INR",
        "stripe_price_id_monthly": None,
        "stripe_price_id_annual": None,
        "limits": {
            "max_devices": 2,
            "max_users": 1,
            "data_retention_days": 7,
            "api_calls_per_day": 1000,
            "alerts_per_month": 50,
            "ml_predictions_per_day": 100,
            "heatmap_access": False,
            "email_notifications": False,
            "sms_notifications": False,
            "mqtt_relay": False,
            "export_csv": False,
            "priority_support": False,
        },
        "features": [
            "2 devices",
            "7-day data history",
            "Basic dashboard",
            "1 user",
        ],
        "color": "#64748b",
        "badge": None,
    },
    "starter": {
        "name": "starter",
        "display_name": "Starter",
        "tagline": "For small businesses and fleet owners",
        "price_monthly": 1999,
        "price_annual": 19990,
        "currency": "INR",
        "stripe_price_id_monthly": "price_starter_monthly_placeholder",
        "stripe_price_id_annual": "price_starter_annual_placeholder",
        "limits": {
            "max_devices": 10,
            "max_users": 5,
            "data_retention_days": 30,
            "api_calls_per_day": 10000,
            "alerts_per_month": 500,
            "ml_predictions_per_day": 1000,
            "heatmap_access": True,
            "email_notifications": True,
            "sms_notifications": False,
            "mqtt_relay": True,
            "export_csv": True,
            "priority_support": False,
        },
        "features": [
            "10 devices",
            "30-day data history",
            "Full dashboard",
            "5 users",
            "Email alerts",
            "Heatmap access",
            "CSV export",
            "MQTT relay control",
        ],
        "color": "#3b82f6",
        "badge": "Popular",
    },
    "professional": {
        "name": "professional",
        "display_name": "Professional",
        "tagline": "For growing enterprises and city operators",
        "price_monthly": 7999,
        "price_annual": 79990,
        "currency": "INR",
        "stripe_price_id_monthly": "price_pro_monthly_placeholder",
        "stripe_price_id_annual": "price_pro_annual_placeholder",
        "limits": {
            "max_devices": 100,
            "max_users": 25,
            "data_retention_days": 180,
            "api_calls_per_day": 100000,
            "alerts_per_month": 5000,
            "ml_predictions_per_day": 10000,
            "heatmap_access": True,
            "email_notifications": True,
            "sms_notifications": True,
            "mqtt_relay": True,
            "export_csv": True,
            "priority_support": True,
        },
        "features": [
            "100 devices",
            "180-day data history",
            "Full dashboard + analytics",
            "25 users",
            "Email + SMS alerts",
            "Heatmap + time-slider",
            "ML predictions",
            "Priority support",
            "API access",
        ],
        "color": "#8b5cf6",
        "badge": "Best Value",
    },
    "enterprise": {
        "name": "enterprise",
        "display_name": "Enterprise",
        "tagline": "Custom deployment for city governments & large industry",
        "price_monthly": 0,
        "price_annual": 0,
        "currency": "INR",
        "stripe_price_id_monthly": None,
        "stripe_price_id_annual": None,
        "limits": {
            "max_devices": 999999,
            "max_users": 999999,
            "data_retention_days": 3650,
            "api_calls_per_day": 999999,
            "alerts_per_month": 999999,
            "ml_predictions_per_day": 999999,
            "heatmap_access": True,
            "email_notifications": True,
            "sms_notifications": True,
            "mqtt_relay": True,
            "export_csv": True,
            "priority_support": True,
        },
        "features": [
            "Unlimited devices",
            "10-year data retention",
            "Custom integrations",
            "Unlimited users",
            "Dedicated support",
            "SLA guarantee",
            "On-premise option",
            "Custom ML models",
            "White-label option",
        ],
        "color": "#f59e0b",
        "badge": "Contact Sales",
    },
}
