import { Check } from 'lucide-react';

const rows = [
    ['Measures emissions', 'Interprets emission behaviour'], ['Shows current value', 'Compares against source baseline'], ['Threshold alert', 'Contextual anomaly detection'], ['Assumes sensor data is valid', 'Evaluates sensor confidence'], ['Reports a problem', 'Prioritizes the problem'], ['Separate maintenance information', 'Connects emission behaviour with maintenance prediction'], ['Dashboard / report', 'Decision + recommended action'],
];

export default function HowItComparesPage() {
    return <div className="mx-auto max-w-5xl space-y-9"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[0.14em] text-primary-600">The EMIQ difference</p><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-5xl">Monitoring is a signal.<br />EMIQ turns it into a decision.</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-slate-600 dark:text-slate-300">Move from seeing emissions data to understanding the operating behaviour behind it and knowing the right next step.</p></div><section className="overflow-hidden rounded-3xl bg-slate-950 p-2 shadow-2xl sm:p-4"><div className="grid grid-cols-2 gap-4 border-b border-white/15 px-3 pb-4 pt-3 sm:px-5"><h2 className="text-sm font-bold text-slate-400 sm:text-lg">Existing monitoring</h2><h2 className="text-sm font-bold text-emerald-300 sm:text-lg">EMIQ</h2></div><div>{rows.map(([existing, emiq]) => <div key={existing} className="grid grid-cols-2 gap-4 border-b border-white/10 px-3 py-4 last:border-b-0 sm:px-5 sm:py-5"><p className="pr-2 text-sm leading-5 text-slate-300 sm:text-base">{existing}</p><p className="flex gap-2 text-sm font-semibold leading-5 text-white sm:text-base"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" />{emiq}</p></div>)}</div></section><section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center dark:border-emerald-500/20 dark:bg-emerald-500/10"><p className="text-lg font-bold text-emerald-950 dark:text-emerald-100">EMIQ helps teams focus on the events that matter — earlier, with more confidence and a clear recommended action.</p></section></div>;
}
